// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Thu Mar 17 16:47:09 2022

Signal_in_synchronize_module Signal_in_synchronize_module_inst
(
	.clk_50M(clk_50M_sig) ,	// input  clk_50M_sig
	.rst(rst_sig) ,	// input  rst_sig
	.signal_in(signal_in_sig) ,	// input  signal_in_sig
	.signal_in2(signal_in2_sig) ,	// output  signal_in2_sig
	.signal_in2_out(signal_in2_out_sig) 	// output  signal_in2_out_sig
);

